version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: healthguard-mongo
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthguard

  redis:
    image: redis:7-alpine
    container_name: healthguard-redis
    ports:
      - "6379:6379"
    networks:
      - healthguard
    profiles:
      - with-cache

  api:
    build: .
    container_name: healthguard-api
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./backend/app:/app/backend/app
      - ./ml:/app/ml
    depends_on:
      - mongodb
    networks:
      - healthguard
    command: flask --app backend.app.main run --host=0.0.0.0 --port=5000 --reload

volumes:
  mongodb_data:

networks:
  healthguard:
    driver: bridge
